blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://mika.org/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: 🧑‍💻 MiKa help discord
    url: https://discord.gg/F32UjdJZrR
    about: Common questions are answered here
  - name: 🖥️ MiKa website
    url: https://mika.org/
    about: Guides, troubleshooting, and answers to common questions
